-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 08:33:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(256) NULL,
  `cedula` VARCHAR(10) NULL,
  `telefono` VARCHAR(16) NULL,
  `email` VARCHAR(256) NULL,
  `username` VARCHAR(16) NULL,
  `password` VARCHAR(32) NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usario_roles_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_usario_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lugar` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(256) NULL,
  `direccion` VARCHAR(256) NULL,
  `telefono` VARCHAR(16) NULL,
  `imagen` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`boleteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`boleteria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(256) NULL,
  `descripcion` LONGTEXT NULL,
  `imagen` VARCHAR(256) NULL,
  `fecha` DATE NULL,
  `hora_ini` DATETIME NULL,
  `hora_fin` DATETIME NULL,
  `precio` DECIMAL(2,18) NULL,
  `usuario_id` INT NOT NULL,
  `lugar_id` INT NOT NULL,
  `maximo` INT NULL,
  `disponible` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_usario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_evento_lugar1_idx` (`lugar_id` ASC) VISIBLE,
  CONSTRAINT `fk_evento_usario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_lugar1`
    FOREIGN KEY (`lugar_id`)
    REFERENCES `mydb`.`lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento_boleteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento_boleteria` (
  `evento_id` INT NOT NULL,
  `boleteria_id` INT NOT NULL,
  INDEX `fk_evento_boleteria_evento1_idx` (`evento_id` ASC) VISIBLE,
  INDEX `fk_evento_boleteria_boleteria1_idx` (`boleteria_id` ASC) VISIBLE,
  CONSTRAINT `fk_evento_boleteria_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_boleteria_boleteria1`
    FOREIGN KEY (`boleteria_id`)
    REFERENCES `mydb`.`boleteria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservacion` (
  `id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservacion_usario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_reservacion_evento1_idx` (`evento_id` ASC) VISIBLE,
  INDEX `fk_reservacion_estado1_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservacion_usario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacion_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacion_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
